# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt-GUI/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 608)
        MainWindow.setMinimumSize(QtCore.QSize(458, 608))
        MainWindow.setMaximumSize(QtCore.QSize(458, 608))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(458, 608))
        self.centralwidget.setMaximumSize(QtCore.QSize(458, 608))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 439, 43))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.MinecraftPath = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.MinecraftPath.setContentsMargins(0, 0, 0, 0)
        self.MinecraftPath.setObjectName("MinecraftPath")
        self.MCPathName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.MCPathName.setObjectName("MCPathName")
        self.MinecraftPath.addWidget(self.MCPathName)
        self.MCPathText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.MCPathText.setEnabled(True)
        self.MCPathText.setFrame(True)
        self.MCPathText.setReadOnly(True)
        self.MCPathText.setObjectName("MCPathText")
        self.MinecraftPath.addWidget(self.MCPathText)
        self.MCPathSelect = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.MCPathSelect.setObjectName("MCPathSelect")
        self.MinecraftPath.addWidget(self.MCPathSelect)
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(10, 10, 439, 41))
        self.Title.setObjectName("Title")
        self.UpdateStart = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateStart.setGeometry(QtCore.QRect(10, 550, 439, 51))
        self.UpdateStart.setObjectName("UpdateStart")
        self.DeleteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteBtn.setGeometry(QtCore.QRect(330, 440, 111, 23))
        self.DeleteBtn.setObjectName("DeleteBtn")
        self.UpdateMods = QtWidgets.QLabel(self.centralwidget)
        self.UpdateMods.setGeometry(QtCore.QRect(10, 480, 441, 31))
        self.UpdateMods.setObjectName("UpdateMods")
        self.UpdateProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.UpdateProgress.setGeometry(QtCore.QRect(18, 520, 421, 21))
        self.UpdateProgress.setProperty("value", 0)
        self.UpdateProgress.setObjectName("UpdateProgress")
        self.InstalleModsTitle = QtWidgets.QLabel(self.centralwidget)
        self.InstalleModsTitle.setGeometry(QtCore.QRect(20, 140, 421, 31))
        self.InstalleModsTitle.setObjectName("InstalleModsTitle")
        self.DeleteCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.DeleteCheck.setGeometry(QtCore.QRect(20, 440, 161, 21))
        self.DeleteCheck.setObjectName("DeleteCheck")
        self.InstalledModsList = QtWidgets.QListWidget(self.centralwidget)
        self.InstalledModsList.setGeometry(QtCore.QRect(20, 180, 421, 241))
        self.InstalledModsList.setObjectName("InstalledModsList")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ModsUpdater"))
        self.MCPathName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Minecraft:</span></p></body></html>"))
        self.MCPathSelect.setText(_translate("MainWindow", "Select"))
        self.Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Mods updater v2</span></p></body></html>"))
        self.UpdateStart.setText(_translate("MainWindow", "Start updating"))
        self.DeleteBtn.setText(_translate("MainWindow", "Delete"))
        self.UpdateMods.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Update:</span></p></body></html>"))
        self.InstalleModsTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Installed mods:</span></p></body></html>"))
        self.DeleteCheck.setText(_translate("MainWindow", "Delete unused mods"))
